import { Services } from "@/types";

export const SERVICES: Services[] = [
    {
        id: 1,
        imgSrc: "/images/service-icons/service-icon-1.webp",
        name: "Dental Checkup",
        text: "Routine examination and cleaning to maintain healthy teeth and gums.",
        href: "/#dental-checkup",
        idStr: "dental-checkup",
    },
    {
        id: 2,
        imgSrc: "/images/service-icons/service-icon-2.webp",
        name: "Pediatrician",
        text: "Routine checkups and care to monitor healthy growth and development in children.",
        href: "/#pediatrician",
        idStr: "pediatrician",
    },
    {
        id: 3,
        imgSrc: "/images/service-icons/service-icon-3.webp",
        name: "Eye Care",
        text: "Comprehensive eye exams and vision care to maintain optimal eye health and sight.",
        href: "/#eye-care",
        idStr: "eye-care",
    },
    {
        id: 4,
        imgSrc: "/images/service-icons/service-icon-4.webp",
        name: "ENT",
        text: "Diagnosis and treatment of ear, nose, and throat conditions for better health.",
        href: "/#ent",
        idStr: "ent",
    },
    {
        id: 5,
        imgSrc: "/images/service-icons/service-icon-5.webp",
        name: "General OPD",
        text: "General consultations and diagnosis to address everyday health concerns and illnesses.",
        href: "/#general-opd",
        idStr: "general-opd",
    },
    {
        id: 6,
        imgSrc: "/images/service-icons/service-icon-6.webp",
        name: "Orthopedic",
        text: "Expert care for bones, joints, and muscles to restore mobility and reduce pain.",
        href: "/#orthopedic",
        idStr: "orthopedic",
    },
    {
        id: 7,
        imgSrc: "/images/service-icons/service-icon-7.webp",
        name: "Cardiologist",
        text: "Specialized heart care and diagnostics to monitor and maintain cardiovascular health.",
        href: "/#cardiologist",
        idStr: "cardiologist",
    },
    {
        id: 8,
        imgSrc: "/images/service-icons/service-icon-8.webp",
        name: "Gynecologist",
        text: "Comprehensive women's health care covering reproductive wellness and routine examinations.",
        href: "/#gynecologist",
        idStr: "gynecologist",
    },
    {
        id: 9,
        imgSrc: "/images/service-icons/service-icon-9.webp",
        name: "General & Drive Ward",
        text: "Inpatient care and monitoring for general medical conditions and post-procedure recovery.",
        href: "/#general-and-drive-ward",
        idStr: "general-and-drive-ward",
    },
    {
        id: 10,
        imgSrc: "/images/service-icons/service-icon-10.webp",
        name: "24 hr Emergency",
        text: "Round-the-clock urgent care for critical and life-threatening medical emergencies.",
        href: "/#24hr-emergency",
        idStr: "24hr-emergency",
    },
    {
        id: 11,
        imgSrc: "/images/service-icons/service-icon-11.webp",
        name: "ICU/NICU",
        text: "Intensive critical care and monitoring for severely ill adults and newborns.",
        href: "/#icu-or-nicu",
        idStr: "icu-or-nicu",
    },
    {
        id: 12,
        imgSrc: "/images/service-icons/service-icon-12.webp",
        name: "Minor Major OT",
        text: "Surgical procedures ranging from minor operations to major life-saving interventions.",
        href: "/#minor-major-ot",
        idStr: "minor-major-ot",
    },
    {
        id: 13,
        imgSrc: "/images/service-icons/service-icon-13.webp",
        name: "Radiology",
        text: "Advanced imaging and diagnostic scans to accurately detect and evaluate medical conditions.",
        href: "/#radiology",
        idStr: "radiology",
    },
    {
        id: 14,
        imgSrc: "/images/service-icons/service-icon-14.webp",
        name: "Endoscopy & Colonoscopy",
        text: "Minimally invasive internal examinations to diagnose digestive tract conditions and disorders.",
        href: "/#endoscopy-and-colonoscopy",
        idStr: "endoscopy-and-colonoscopy",
    },
    {
        id: 15,
        imgSrc: "/images/service-icons/service-icon-15.webp",
        name: "General Surgery",
        text: "Surgical treatment for a broad range of conditions affecting the abdomen and beyond",
        href: "/#general-surgery",
        idStr: "general-surgery",
    },
    {
        id: 16,
        imgSrc: "/images/service-icons/service-icon-16.webp",
        name: "Neuro Surgery",
        text: "Specialized surgical care for brain, spine, and nervous system conditions and disorders.",
        href: "/#neuro-surgery",
        idStr: "neuro-surgery",
    },
    {
        id: 17,
        imgSrc: "/images/service-icons/service-icon-16.webp",
        name: "Psychiatry",
        text: "Compassionate mental health care for diagnosing and treating psychological and emotional disorders.",
        href: "/#psychiatry",
        idStr: "psychiatry",
    },
];